version: "3"
services:
  server:
    container_name: "books-gql-server"
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
