version: "3"
services:
  client:
    container_name: "books-gql-client"
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    environment: 
      - NODE_ENV=production
      - GQL_SERVER_PORT=${PORT}
    ports:
      - "3000:3000"
    depends_on: 
      - server
  server:
    container_name: "books-gql-server"
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
